#ifndef MYSQLPROXY_SYSTEM_CONFIG_HPP
#define MYSQLPROXY_SYSTEM_CONFIG_HPP

#include <boost/config.hpp>

#if defined(MYSQLPROXY_SYSTEM_SOURCE)
#  define MYSQLPROXY_SYSTEM_API BOOST_SYMBOL_EXPORT
#else
#  define MYSQLPROXY_SYSTEM_API BOOST_SYMBOL_IMPORT
#endif

#endif // MYSQLPROXY_SYSTEM_CONFIG_HPP